apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
     app: mypod_face_detection_app
spec:
  containers:
  - name: face-detection
    image: 8149080856/face:v1
    ports:
    - containerPort: 8000

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mypod-dep
#   labels:
#      app: mypod_face_detection_app
# spec:
#   containers:
#   - name: face_detection
#     image: 8149080856/face:v1
#     ports:
#     - containerPort: 8000

