name:   CI pipeline by using github action to build and push DockerImage
on:
        push:
                branches:
                 -      Face-Detection-Minor/docker-compose
jobs:
        build:
                runs-on:        ubuntu-latest
                steps:
                   - name:   checkout code
                     uses:   actions/checkout@v2 #name-of-the-repo @ specific version 
                     
                   - name:   Login to Docker Hub
                                 #name-of-the-repo @ specific version 
                     uses:   docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                     with:
                             username: ${{ secrets.DOCKER_USERNAME }} #use DOCKER_USERNAME from repo. secrets
                             password: ${{ secrets.DOCKER_PASSWORD }} #use DOCKER_PASSWORD from repo. secrets
   
                   - name: Extract metadata (tags, labels) for Docker
                     id: meta
                      #name-of-the-repo @ specific version 
                     uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
                     with:
                             images: 8149080856/devops_21_practice #username/repo:tag

                   - name: Build and push Docker image
                         #name-of-the-repo @ specific version 
                     uses: docker/build-push-action@v2     #docker/build-push-action GitHub Action, which provides the functionality to build and push Docker images.
                     with: #following lines are contain input parameters for the action.
                             context: .  #use the dockerfile from here
                             push: true
                             tags: 8149080856/devops_21_practice:updated #username/repo:tag


